/* SPDX-License-Identifier: BSD-2-Clause */
/*
 * iicbus_if.h — KOBJ method descriptor externs for the iicbus interface.
 *
 * In FreeBSD these are generated by INTERFACE(iicbus) from iicbus_if.m.
 * In the shim they are plain structs defined in bsc_kobj_descriptors.c.
 *
 * Only the three methods used by bcm2835_bsc.c need to be present:
 *   iicbus_reset    → bcm_bsc_iicbus_reset
 *   iicbus_callback → iicbus_null_callback
 *   iicbus_transfer → bcm_bsc_transfer
 */
#ifndef _IICBUS_IF_H_
#define _IICBUS_IF_H_

#include <shim_core.h>  /* struct kobjop_desc */

extern struct kobjop_desc iicbus_callback_desc;
extern struct kobjop_desc iicbus_reset_desc;
extern struct kobjop_desc iicbus_transfer_desc;

#endif /* _IICBUS_IF_H_ */
